### ISSUE TITLE
gradlew assembleRelease 自动注册不好用

### ISSUE THREAD

**Issue by 870408620** [luckybilly/AutoRegister#11]

**Comment by luckybilly** [comment]
说具体一点吧

**Comment by 870408620** [comment]
就是 在命令行 输入gradlew assembleRelease  然后 打包出来的apk  安装到手机上 用cc。obtainbuild的跳转都失效了  然后用 菜单栏的build--》generate sign apk 就好用

**Comment by luckybilly** [comment]
命令行打包要加上module名称：
gradlew app:assembleRelease

**Comment by luckybilly** [comment]
![image](https://user-images.githubusercontent.com/4155835/44440093-3639d680-a5f9-11e8-978f-4a8d7c8b7fbd.png)

**Comment by 870408620** [comment]
我就是 这样 简写的 gradlew asR  我试试你的命令

**Comment by 870408620** [comment]
好的 我知道了 必须是全拼 简写就不好用了

**Comment by luckybilly** [comment]
@870408620 谢谢你的反馈，后续我会考虑支持一下这种简写。

另外，说明一下，以免其他使用AutoRegister的开发者误解：这个issue的主题与AutoRegister无关，是属于[CC](https://github.com/luckybilly/CC)的讨论范畴
