### ISSUE TITLE
arr是否支持自动注入

### ISSUE THREAD

**Issue by json-pu** [luckybilly/AutoRegister#12]
你好，我是一个组件的项目，需要打成aar上传到代码仓库，但是我发现AutoRegister并没生成注入代码，请问需要如何解决

**Comment by luckybilly** [comment]
AutoRegister插件在library module编译时是不会工作的

这么做的原因是：
1. autoregister插件的主要作用是解决android开发中**跨module注册及调用**的问题：module之间解耦
2. 插件只需要在主app module中执行一次即可扫描所有的类进行统一注册，其它library module无需再各自运行一遍插件
3. library module里的代码可以直接引用到其内部的类，对自动注册功能需求不强烈
4. AutoRegister的诞生，最开始是为组件化框架[CC](https://github.com/luckybilly/CC)提供跨module的组件自动注册功能的，组件module可切换编译方式（library/application），以library编译时显然不希望它无意义地运行一次插件扫描

你需要的解决办法：
1. fork一份AutoRegister的代码
2. 修改[此处](https://github.com/luckybilly/AutoRegister/blob/0ca47fd8c6439580779e193d6af27776594a14ee/autoregister/src/main/groovy/com/billy/android/register/RegisterPlugin.groovy#L22)，删除application的判断。
3. 编译插件，并将它发布到你自己的maven仓库
4. 在项目中使用它

**Comment by json-pu** [comment]
非常感谢你，你就是活雷锋啊

**Comment by luckybilly** [comment]
@json-pu 觉得好用的话可以给AutoRegister点个star : )

**Comment by json-pu** [comment]
已star，你这个项目确实解决了很大的痛点，我现在按你的方法修改了
并把Extension改为
`def android = project.extensions.getByType(LibraryExtension)`
但是报错：
Transforms with scopes '[SUB_PROJECTS, SUB_PROJECTS_LOCAL_DEPS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.

**Comment by luckybilly** [comment]
还要修改一下transform的[scope](https://github.com/luckybilly/AutoRegister/blob/0ca47fd8c6439580779e193d6af27776594a14ee/autoregister/src/main/groovy/com/billy/android/register/RegisterTransform.groovy#L38)

[参考资料](https://groups.google.com/forum/#!topic/adt-dev/Ga4QHR9P9QU)
~~~
Transforms on Library projects can only apply to Scope.PROJECT and Scope.PROJECT_LOCAL_DEPS. If you apply to more scopes it'll fail to apply (and should display an error).
~~~
![image](https://user-images.githubusercontent.com/4155835/53419343-aa27c200-3a14-11e9-9694-e8e4ce7a2a46.png)

**Comment by json-pu** [comment]
感谢大神，我现在按照你的方法做了，已经能正常运行。但是还有一个问题，autoregister扫描不到引用的代码库即aar，而我scanInterface的子类不是在module里而是在一个代码库中
