### ISSUE TITLE
1.4.1无法插入static 代码块

### ISSUE THREAD

**Issue by xchengDroid** [luckybilly/AutoRegister#14]
android studio 3.3.2  gradle 3.3.2 无法插入static{ }中 请问这个是被取消了吗

**Comment by luckybilly** [comment]
请问你是如何配置的？
如果要插入到static块中，codeInsertToMethodName可以不配置(取默认值)，或者配置为: '<clinit>'

https://github.com/luckybilly/AutoRegister/blob/0ca47fd8c6439580779e193d6af27776594a14ee/autoregister/src/main/groovy/com/billy/android/register/RegisterInfo.groovy#L89

**Comment by xchengDroid** [comment]
不设置的情况  下无法 插入 static{}中！我再试试吧
