### ISSUE TITLE
集成Android resgurad之后，被执行了两次导致注册失败

### ISSUE THREAD

**Issue by perseusyang** [luckybilly/AutoRegister#15]

**Comment by luckybilly** [comment]
能不能描述得更详细一些?注册失败指的是编译时报错还是没有生成字节码？gradle console中autoregister相关的日志贴一下看看

**Comment by perseusyang** [comment]
偶现的bug，上午的时候一直出现，刚刚又复现时，发现无法复现了，可能跟编译代码的机器的性能有关，我再试几次，出现问题时报的bug,应该是两个自动注册的任务都在执行，导致报错，腾讯的Android regguard在执行时我看到的log是执行了两次transform的操作的，可能是上次的没有执行完，第二次执行的过程中报错了，之前的log,被冲刷掉了
register insert code cost time: 63 ms
register cost time: 631 ms
:app:processReleaseJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:app:transformClassesAndResourcesWithProguardForRelease
ProGuard, version 5.3.3
Reading input...

**Comment by luckybilly** [comment]
再报错的时候把报错日志贴一下吧，确定一下是哪里报错，报的什么错
