### ISSUE TITLE
这是什么问题：java.lang.IncompatibleClassChangeError？

### ISSUE THREAD

**Issue by zhuangjiahua** [luckybilly/AutoRegister#16]
java.lang.IncompatibleClassChangeError: The method 'void com.xxx.core.app.ModuleManager.registModule(com.xxx.core.app.IModuleApplication)' was expected to be of type direct but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

**Comment by seelikes** [comment]
有可能是这里需要一个static方法，而你给出的是一个object的成员方法

**Comment by zhuangjiahua** [comment]
好的，我试一下

**Comment by Nstd** [comment]
有同样的问题。
如果使用非静态方式注入，生成的注入代码中，会调用`super.register(...)`，但`codeInsertToClassName`并没有继承任何类。

以下是反编译的结果：
![image](https://user-images.githubusercontent.com/3004225/58405410-ef05d800-8099-11e9-8d53-0cbff5922ff2.png)

**Comment by luckybilly** [comment]
@zhuangjiahua  v1.4.2版本已修复这个问题，烦请验证！
