### ISSUE TITLE
registerMethodName--> No static method

### ISSUE THREAD

**Issue by daxiong--** [luckybilly/AutoRegister#18]
--------配置日志成功
com/yuan/sign/App
com/yuan/main/App
generate code into:com/yuan/root/AppInitManager.class
register insert code cost time: 6 ms
register cost time: 186 ms

--------运行时失败-------
java.lang.NoSuchMethodError: No static method registerApp(Lcom/yuan/root/IApplication;)V in class Lcom/yuan/root/AppInitManager; or its super classes (declaration of 'com.yuan.root.AppInitManager' appears in /data/app/com.yuan.next-l5TsRwNaHmaPJiUlanPFjg==/split_lib_slice_2_apk.apk)

-----------------注入配置------------
registerInfo = [
            [
                    'scanInterface'            :     'com.yuan.root.IApplication'
                    ,'scanSuperClasses'        :     ['com.yuan.root.BaseApplication']
                    ,'codeInsertToClassName'   :     'com.yuan.root.AppInitManager'
                    ,'registerMethodName'  :     'registerApp'
                    , 'exclude'                 : [
                    'com.yuan.root.BaseApplication'.replaceAll('\\.', '/')
                    ,'com/yuan/next/App'.replaceAll('\\.', '/')
                ]
            ]
    ]

**Comment by daxiong--** [comment]
开发语言 kotlin

**Comment by luckybilly** [comment]
未配置`codeInsertToMethodName`时，生成的代码默认插入到`codeInsertToClassName`指定的类的static块中，所以需要`registerMethodName`方法是static的

**Comment by luckybilly** [comment]
![image](https://user-images.githubusercontent.com/4155835/61515420-2444fb80-aa35-11e9-9257-5d8388fabc38.png)

**Comment by daxiong--** [comment]
我把codeInsertToClassName对应的类切换回Java写，ok了

**Comment by daxiong--** [comment]
package com.yuan.root

class AppInitManager {

    companion object {
        private  val applicationList = ArrayList<IApplication>()

        fun registerApp(iApplication: IApplication) {
            iApplication?.let { applicationList.add(it) }
        }

        fun init() {
            for (application in applicationList) {
                application.init()
            }
//            applicationList.clear()
        }

        override fun toString(): String {
            val sb = StringBuffer()
            for (application in applicationList) {
                sb.append(application.javaClass.name)
            }
            return sb.toString()
        }
    }


}

**Comment by daxiong--** [comment]
package com.yuan.root;

import androidx.annotation.NonNull;

import java.util.ArrayList;

public class AppInitManager {
    private static ArrayList<IApplication> applications = new ArrayList<>();
    public static void registerApp(IApplication iApplication){
        if (iApplication != null) {
            applications.add(iApplication);
        }
    }

    public static void init(){
        for (IApplication application : applications) {
            application.init();
        }
    }


    public static String print() {
        StringBuffer sb = new StringBuffer();
        for (IApplication application : applications) {
            sb.append(application.getClass().getName()).append("/n");
        }
        return sb.toString();
    }
}

**Comment by daxiong--** [comment]
我把codeInsertToClassName对应的类切换回Java写，ok了

**Comment by daxiong--** [comment]
确实如你所说

**Comment by daxiong--** [comment]
kotlin -- >  没配置 codeInsertToMethodName，配置了就好了

**Comment by luckybilly** [comment]
@daxiong-- 很高兴AutoRegister能帮到你，为开源项目点star是对它最好的支持哦~ 
另外，可以进入我的github主页，看看其它项目是否对你有所帮助！ : )

**Comment by daxiong--** [comment]
大赞
