### ISSUE TITLE
请教大神asm问题

### ISSUE THREAD

**Issue by wxb871127** [luckybilly/AutoRegister#19]
if ((opcode >= Opcodes.IRETURN && opcode <= Opcodes.RETURN))
各种网页及论坛都是这么写，这个话的效果是在方法的最后一行进行修改
如果要在方法的第一行进行修改应如何判断
其中Opcodes.IRETURN就是jvm的ireturn指令表示从当前方法返回int
按照这个解析似乎if判断并不对吧，请大神指点

**Comment by luckybilly** [comment]
1. 在函数的第一行新增代码：在visitCode方法里实现， 参考我的[AndAOP](https://github.com/luckybilly/AndAOP/blob/c7655bc210ea4bb7bc9d4dad0a92bfc5bb7914e5/aop/src/main/groovy/com/billy/aop/AndAopProcessor.groovy#L181)
> visitCode方法将会在ASM开始访问某一个方法时调用，因此这个方法一般可以用来在进入分析JVM字节码之前来新增一些字节码
> 
2. 返回值的类型有多个，这些类型的在Opcodes中定义的最小值是`Opcodes.IRETURN`， 最大值是 `Opcodes. RETURN`，所以，我们可以用`if ((opcode >= Opcodes.IRETURN && opcode <= Opcodes.RETURN))`来判断是否为return语句
