### ISSUE TITLE
能否支持Library的扫描

### ISSUE THREAD

**Issue by luwei2012** [luckybilly/AutoRegister#22]
看RegisterPlugin里一进去就判断是否是application，里面详细的逻辑还没看懂，想问下是否有办法支持library使用呢，我实际测试结果来看在library的build.gradle里配置autoregister是不生效的

**Comment by luckybilly** [comment]
@luwei2012 你好，我的理解library是不需要支持自动注册的：
- library module内部的源码是可以直接使用的
- library打包成aar时，它所依赖的其它library或者第三方库只是作为依赖项，并不会打包在aar内，可能被exclude的，如果依赖包中的类被注册但是exclude了会出现ClassNotFoundException
- 如果在library编译时执行注册，不管是单独编译成aar或者编译集成到主app中，都可能会导致注册不完整（没有被改library依赖的包中如果存在符合注册条件的类将不会被扫描到）

或许你有必须要在library中使用自动注册的需求场景，不妨说明一下？
