### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by ooftf** [luckybilly/AutoRegister#23]
Execution failed for task ':app:transformClassesWithAuto-registerForDebug'.
> java.lang.ArrayIndexOutOfBoundsException (no error message)

经过排查好像是CodeScanProcessor类的
//refer hack class when object init
    boolean scanClass(InputStream inputStream, String filePath) {
        ClassReader cr = new ClassReader(inputStream)
        ClassWriter cw = new ClassWriter(cr, 0)
        ScanClassVisitor cv = new ScanClassVisitor(Opcodes.ASM5, cw, filePath)
        cr.accept(cv, ClassReader.EXPAND_FRAMES)
        inputStream.close()

        return cv.found
    }
中的new ClassReader(inputStream)报出的错误，这个地方扫描的类名好像是module-info.class具体什么原因产生的我也不懂。。。希望能改进一下

**Comment by ooftf** [comment]
貌似是和gson  2.8.6版本不兼容导致的

**Comment by ooftf** [comment]
这个还会更新吗

**Comment by naturs** [comment]
对，我这把gson升级到2.8.6也会编译失败，2.8.5没问题

**Comment by leigao109** [comment]
gson 2.8.6里面用到了java 9的模块化，目前我把'module-info'给排除了，可以编译通过，但不知道会不会有其他影响。

**Comment by zhuangjiahua** [comment]
我这里用的gson 2.8.5，但还是会报这个错，请问怎么解决？

**Comment by zhuangjiahua** [comment]
@leigao109 ：
gson 2.8.6里面用到了java 9的模块化，目前我把'module-info'给排除了，可以编译通过，但不知道会不会有其他影响。

module-info这个是什么？

**Comment by ooftf** [comment]
应该是你用的包里面，间接引用了gons 2.8.6，你可以打印一下依赖树，看最终引用版本，如果是2.8.6，强制改成2.8.5

**Comment by ooftf** [comment]
这个问题已经在https://github.com/ooftf/AutoRegister 解决

**Comment by liujingxing** [comment]
@leigao109 如何排除的module-info.class
