### ISSUE TITLE
请教一个问题，在RegisterTransform.groovy里面扫描到了那些实现了IRouteGroup的class后有办法执行IRouteGroup的loadInto方法吗？

### ISSUE THREAD

**Issue by alen252** [luckybilly/AutoRegister#24]
你好，请教问题，如题。

**Comment by luckybilly** [comment]
有，请看文档

**Comment by alen252** [comment]
> 有，请看文档

我是指在RegisterTransform.groovy里面执行 loadInto方法，也就是在Transform阶段。我目前遇到执行loadInto方法的时候，报java.lang.NoClassDefFoundError，比如
@Override
  public void loadInto(Map<String, RouteMeta> atlas) {
    atlas.put("/main/wade", RouteMeta.build(RouteType.ACTIVITY, MainActivity.class, "/main/wade", "main", null, -1, -2147483648));
  }
执行Method.invoke()执行的时候MainActivity.class会找不到
