### ISSUE TITLE
This feature requires ASM7

### ISSUE THREAD

**Issue by zhuangjiahua** [luckybilly/AutoRegister#35]
升级AGP至7.0.2，编译报以下错误：

`
* What went wrong:
Execution failed for task ':App:transformClassesWithAuto-registerForAppDebug'.
> This feature requires ASM7

`

**Comment by zhuangjiahua** [comment]
Any help?

**Comment by dashingqi** [comment]
你可以将这个项目中  【CodeInsertProcessor】 和【CodeScanProcessor】类中 关于 【Opcodes.ASM6】使用 替换成 【Opcodes.ASM7】
------------------------------------
或者可以把字节码相关操作的代码 封装成一个类，这个类实现Opcodes接口 之后升级了就不用做适配了

**Comment by dashingqi** [comment]
> Any help?

- 你可以将这个项目中 【CodeInsertProcessor】 和【CodeScanProcessor】类中 关于 【Opcodes.ASM6】使用 替换成 【Opcodes.ASM7】
- 或者可以把字节码相关操作的代码 封装成一个类，这个类实现Opcodes接口 之后升级了就不用做适配了

**Comment by zhuangjiahua** [comment]
> > Any help?
> 
> * 你可以将这个项目中 【CodeInsertProcessor】 和【CodeScanProcessor】类中 关于 【Opcodes.ASM6】使用 替换成 【Opcodes.ASM7】
> * 或者可以把字节码相关操作的代码 封装成一个类，这个类实现Opcodes接口 之后升级了就不用做适配了

也不是没想过自己拉代码下来自己适配一下，只是引用了那么多第三方库，如果很多都要自己适配的话，就忙不过来了，而且拉下来往往要折腾好一番才能先确保编译通过，然后才能做适配等工作，还是很耗时的；
目前我先解决Android适配的问题先，然后再来看这问题，这个还不太急；

**Comment by zhuangjiahua** [comment]
已Fork一份，自己解决了。

**Comment by wangchenyan** [comment]
可以试试 https://github.com/wangchenyan/AutoRegister  支持设置 ASM 版本
