### ISSUE TITLE
如题，请教一个问题：这个函数代表什么意思？

### ISSUE THREAD

**Issue by Neacy** [luckybilly/AutoRegister#9]
@Override
        void visitMaxs(int maxStack, int maxLocals) {
            super.visitMaxs(maxStack + 4, maxLocals)// 这个函数代表什么意思？ 能否解答一下参数的意思。
        }

看了好久没明白这点，谢谢！

**Comment by luckybilly** [comment]
maxStack用于指定函数中操作数栈的最大尺寸
maxLocals用于指定函数中局部变量的最大数
具体使用方法可参考ASM手册
PS：一个更简单的方法是，创建ClassWriter时指定flag（`new ClassWriter(cr, ClassWriter.COMPUTE_MAXS)`）让ASM自动来计算，这样就不用复写visitMaxs函数了

**Comment by Neacy** [comment]
感谢 感谢。
